config/routes.rb
Rails.application.routes.draw do

  resources :vendors

  devise_for :users
    root 'map#index'

  resources :categories
  resources :users

  get 'map' => 'maps#index'

end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :registerable,
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!
  
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation) #:category, 
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  
  <div class="actions">
    <%= f.submit :class => 'btn' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div id="header"><h1>Edit User</h1></div>
<div class="edit-container">
<%= render 'form' %>
		<%= link_to 'Show', @user , :class => 'btn' %>&nbsp;
		<%= link_to 'Back', users_path, :class => 'btn' %>
</div>

app/views/users/index.html.erb
<table>
  
  <thead>
    <tr>
      <th>Email</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
      
    <% @users.each do |user| %>

      <tr>
        <td><%= user.email %></td>
        <td>
          <%= link_to 'View', user %>
          <%= link_to 'Edit', edit_user_path(user) %>
          <%= link_to 'Delete', user_path(user), method: :delete, data: { confirm: "Are you sure you want to delete this user?"} %>
        </td>
      </tr>

    <% end %>

  </tbody>
</table>

app/views/users/new.html.erb
<div id="header"><h1>New User</h1></div>
<div class="edit-container">
<%= render 'form' %>

<%= link_to 'Back', users_path, :class => 'btn' %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<div class="btns">
  <%= link_to 'Edit', edit_user_path(@user), :class => 'btn backend-btn' %>
  <%= link_to 'Back', users_path, :class => 'btn backend-btn' %>
</div>