config/routes.rb
Rails.application.routes.draw do

  resources :vendors

  devise_for :users
    root 'map#index'

  resources :categories
  resources :users

  get 'map' => 'maps#index'

end

app/models/vendor.rb
class Vendor < ActiveRecord::Base

	has_many :vendor_categories
	has_many :categories, through: :vendor_categories

	geocoded_by :postcode 
	after_validation :geocode

	PARISHES = ["St Helier", "St Clement", "St Saviour", "St Martin", "Grouville", "Trinity", "St John", "St Mary", "St Ouen", "St Peter", "St Lawrence", "St Brelade"].sort

	validates_presence_of :latitude, :longitude, :title

end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController

  before_filter :authenticate_user!

  before_action :set_vendor, only: [:show, :edit, :update, :destroy]

  def index
    @vendors = Vendor.all
    @hash = Gmaps4rails.build_markers(@vendors) do |vendor, marker|
      marker.lat vendor.latitude
      marker.lng vendor.longitude
      marker.infowindow "<h1 class='vendor-title'>" + vendor.title + "</h1>" + "<br>" + 
        "<img src='#{vendor.picture}' class='info-image'>" + "<br>" + "<div class='vendor-description'>" + vendor.description + "<br>" + "Categories:  " + vendor.categories.map(&:name).join(', ')
    end
  end

  def show
  end

  def new
    @vendor = Vendor.new
  end

  def edit
  end

  def create
    @vendor = Vendor.new(vendor_params)

    if @vendor.save
      redirect_to @vendor, notice: 'Vendor was successfully created.' 
    else
      render :new
    end

  end

  def update
    @vendor.parish=params[:parish]
    @vendor.category_ids=params[:vendor][:category_ids]

    if @vendor.update(vendor_params)
      redirect_to @vendor, notice: "Vendor was successfully updated"
    else
      render :edit
    end
  end

  def destroy
    @vendor.destroy
    redirect_to vendors_url, notice: "Vendor was successfully deleted"
  end

  private
    def set_vendor
      @vendor = Vendor.find(params[:id])
    end

    def vendor_params
      params.require(:vendor).permit(:title, :address, :parish, :postcode, :description, :picture, :contact_name, :contact_tel, :contact_email, :category_id => [])
    end
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/_form.html.erb
<%= form_for(@vendor) do |f| %>
  <% if @vendor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vendor.errors.count, "error") %> prohibited this vendor from being saved:</h2>

      <ul>
      <% @vendor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :parish %><br>
    <select name="vendor[parish]">
    <option></option>
    <option>Saint Helier</option>
    <option>Grouville</option>
    <option>St Brelade</option>
    <option>St Clement</option>
    <option>St Clement</option>
    <option>St John</option>
    <option>St Lawrence</option>
    <option>St Martin</option>
    <option>St Mary</option>
    <option>St Ouen</option>
    <option>St Peter</option>
    <option>St Saviour</option>
    <option>Trinity</option>
    </select>
  </div>
  <div class="field">
    Formatted address for Geocoding (if co-ordinates are known leave this field blank)<br>
    If vendor latitude/longitude co-ordinates are unknown enter the address formatted for google maps (without commas or special character etc.), eg:<br><br>
    Somestreet Someparish Jersey<br>
    <%= f.text_field :postcode %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= hidden_field_tag "vendor[category_ids][]", nil %>
    <% Category.all.each do |category| %>
      <%= check_box_tag "vendor[category_ids][]", category.id,
       @vendor.category_ids.include?(category.id), id: dom_id(category) %>
      <%= label_tag dom_id(category), category.name %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="field">
    <%= f.label :contact_name %><br>
    <%= f.text_field :contact_name %>
  </div>
  <div class="field">
    <%= f.label :contact_tel %><br>
    <%= f.text_field :contact_tel %>
  </div>
  <div class="field">
    <%= f.label :contact_email %><br>
    <%= f.text_field :contact_email %>
  </div>
  <div class="actions">
    <%= f.submit 'Create Vendor', :class => 'btn' %>
  </div>
<% end %>

app/views/vendors/edit.html.erb
<h1>Editing vendor</h1>

<%= render 'form' %>

<%= link_to 'Show', @vendor %> |
<%= link_to 'Back', vendors_path %>

app/views/vendors/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<div id="header"><h1>Vendors</h1></div>
<div class="container">
<table>
  <thead>
    <tr>

      <th class="table-header">Latitude</th>
      <th class="table-header">Longitude</th>
      <th class="table-header">Title</th>
      <th class="table-header">Address</th>
      <th class="table-header">Parish</th>
      <th class="table-header">Postcode</th>
      <th class="table-header">Description</th>
      <th class="table-header">Category</th>
      <th class="table-header" colspan="3">Options</th>
    </tr>
  </thead>

  <tbody>
    <% @vendors.each do |vendor| %>
      <tr>
        <td class="table-entry"><%= vendor.latitude %></td>
        <td class="table-entry"><%= vendor.longitude %></td>
        <td class="table-entry"><%= vendor.title %></td>
        <td class="table-entry"><%= vendor.address %></td>
        <td class="table-entry"><%= vendor.parish %></td>
        <td class="table-entry"><%= vendor.postcode %></td>
        <td class="table-entry"><%= vendor.description %></td>
        <td class="table-entry"><%= vendor.categories.map(&:name).join(', ') %></td>
        <td class="table-btn"><%= link_to 'Show', vendor %></td>
        <td class="table-btn-alt"><%= link_to 'Edit', edit_vendor_path(vendor) %></td>
        <td class="table-btn"><%= link_to 'Destroy', vendor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stalls', new_vendor_path, class: "btn backend-btn" %>

<div>
  <div id="map" style='width: 100%; height: 500px;'></div>
</div>

<script type="text/javascript">
  
  handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
  
</script>

app/views/vendors/new.html.erb
<h1>New vendor</h1>

<%= render 'form' %>

<%= link_to 'Back', vendors_path %>

app/views/vendors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @vendor.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @vendor.longitude %>
</p>

<p>
  <strong>Title:</strong>
  <%= @vendor.title %>
</p>

<p>
  <strong>Address:</strong>
  <%= @vendor.address %>
</p>

<p>
  <strong>Parish:</strong>
  <%= @vendor.parish %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @vendor.postcode %>
</p>

<p>
  <strong>Description:</strong>
  <%= @vendor.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @vendor.picture %>
</p>

<p>
  <strong>Contact name:</strong>
  <%= @vendor.contact_name %>
</p>

<p>
  <strong>Contact tel:</strong>
  <%= @vendor.contact_tel %>
</p>

<p>
  <strong>Contact email:</strong>
  <%= @vendor.contact_email %>
</p>

<%= link_to 'Edit', edit_vendor_path(@vendor) %> |
<%= link_to 'Back', vendors_path %>